version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: maint
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "pip"
    directory: ".github/latest"
    target-branch: maint
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
