version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: trunk-patch
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "EST5EDT"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 1

  - package-ecosystem: "pip"
    directory: ".github"
    target-branch: trunk-patch
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "EST5EDT"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 1
