ci:
  autoupdate_schedule: quarterly
  autoupdate_branch: 'trunk-patch'
  autofix_prs: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.4.0'
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-case-conflict
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
- repo: https://github.com/glotzerlab/fix-license-header
  rev: v0.2.0
  hooks:
  - id: fix-license-header
    name: Fix license headers (Python)
    types_or: [python, cython]
    args:
    - --license-file=LICENSE
    - --add=Part of GSD, released under the BSD 2-Clause License.
    - --keep-before=#!
  - id: fix-license-header
    name: Fix license headers (C)
    types_or: [c]
    args:
    - --license-file=LICENSE
    - --add=Part of GSD, released under the BSD 2-Clause License.
    - --comment-prefix=//
  - id: fix-license-header
    name: Fix license headers (reStructuredText)
    types_or: [rst]
    args:
    - --license-file=LICENSE
    - --add=Part of GSD, released under the BSD 2-Clause License.
    - --keep-after=.. include
    - --comment-prefix=..
- repo: https://github.com/google/yapf
  rev: 'v0.40.0'
  hooks:
  - id: yapf
    additional_dependencies:
    - toml==0.10.2
- repo: https://github.com/PyCQA/flake8
  rev: '6.0.0'
  hooks:
  - id: flake8
    additional_dependencies:
    - pep8-naming==0.13.3
    - pydocstyle==6.2.3
    - flake8-docstrings==1.6.0
    - flake8-rst-docstrings==0.3.0
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    types_or: [c, c++]
