ci:
  autoupdate_schedule: quarterly
  skip: [clang-format]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.0.1'
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-case-conflict
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
- repo: https://github.com/glotzerlab/fix-license-header
  rev: 686eea86f3a812bf1227a9d074c8328a459c5a66
  hooks:
  - id: fix-license-header
    name: Fix license headers (Python)
    types_or: [python, cython]
    args:
    - --license-file=LICENSE
    - --add=Part of GSD, released under the BSD 2-Clause License.
    - --keep-before=#!
  - id: fix-license-header
    name: Fix license headers (C)
    types_or: [c]
    args:
    - --license-file=LICENSE
    - --add=Part of GSD, released under the BSD 2-Clause License.
    - --comment-prefix=//
  - id: fix-license-header
    name: Fix license headers (reStructuredText)
    types_or: [rst]
    args:
    - --license-file=LICENSE
    - --add=Part of GSD, released under the BSD 2-Clause License.
    - --keep-after=.. include
    - --comment-prefix=..
- repo: https://github.com/google/yapf
  rev: 'v0.31.0'
  hooks:
  - id: yapf
- repo: https://github.com/PyCQA/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
    additional_dependencies:
    - pep8-naming==0.11.1
    - pydocstyle==6.1.1
    - flake8-docstrings==1.6.0
    - flake8-rst-docstrings==0.2.3
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v13.0.0
  hooks:
  - id: clang-format
