ci:
  autoupdate_schedule: quarterly
  autoupdate_branch: 'trunk-patch'
  autofix_prs: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.5.0'
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-case-conflict
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.27
  hooks:
    - id: actionlint
- repo: https://github.com/glotzerlab/fix-license-header
  rev: v0.3.2
  hooks:
  - id: fix-license-header
    name: Fix license headers (Python)
    types_or: [python, cython]
    args:
    - --license-file=LICENSE
    - --add=Part of GSD, released under the BSD 2-Clause License.
    - --keep-before=#!
  - id: fix-license-header
    name: Fix license headers (C)
    types_or: [c]
    args:
    - --license-file=LICENSE
    - --add=Part of GSD, released under the BSD 2-Clause License.
    - --comment-prefix=//
  - id: fix-license-header
    name: Fix license headers (reStructuredText)
    types_or: [rst]
    args:
    - --license-file=LICENSE
    - --add=Part of GSD, released under the BSD 2-Clause License.
    - --keep-after=.. include
    - --comment-prefix=..
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.3.4'
  hooks:
  - id: ruff-format
  - id: ruff
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.2
  hooks:
  - id: clang-format
    types_or: [c, c++]
