version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
    - doxygen

sphinx:
  fail_on_warning: true

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
