version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  fail_on_warning: true

python:
  install:
    - requirements: sphinx-doc/requirements.txt
    - method: setuptools
      path: .

formats:
  - htmlzip
