#:schema https://www.schemastore.org/prek.json

minimum_prek_version = "0.3.8"

[[repos]]
repo = "https://github.com/BlankSpruce/gersemi"
rev = "0.26.1"
hooks = [
  {
    id = "gersemi",
    args = ["--no-warn-about-unknown-commands"]
  }
]

[[repos]]
repo = "builtin"
hooks = [
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
  { id = "check-json" },
  { id = "check-toml" },
  {
    id = "check-yaml",
    exclude = '\.clang-format'
  },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending" },
  { id = "check-added-large-files" },
  { id = "check-executables-have-shebangs" },
  { id = "check-symlinks" },
  { id = "detect-private-key" },
  { id = "check-vcs-permalinks" },
  { id = "check-shebang-scripts-are-executable" },
  { id = "check-illegal-windows-names" },
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "914e7df21a07ef503a81201c76d2b11c789d3fca"  # frozen: v1.7.12
hooks = [
  { id = "actionlint" }
]

[[repos]]
repo = "https://github.com/glotzerlab/fix-license-header"
rev = "96a6da2d22354ecb4dbc50809e9455c7f1e20fe8"  # frozen: v0.4.1
hooks = [
  {
    id = "fix-license-header",
    name = "Fix license headers (Python)",
    types_or = [
      "c",
      "python",
      "cython",
      "rst"
    ],
    args = [
      "--license-file=LICENSE",
      "--add=Part of GSD, released under the BSD 2-Clause License.",
      "--keep-before=#!",
      "--keep-after=.. include"
    ]
  }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "2eeb5678de71a00c0902cbda7105d328432f72cb"  # frozen: v0.16.8
hooks = [
  { id = "ruff-format" },
  { id = "ruff-check" }
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-clang-format"
rev = "e2b496dc2bd8340c2524cb9a2d2a943cde1bb6df"  # frozen: v23.1.1
hooks = [
  {
    id = "clang-format",
    types_or = [
      "c",
      "c++"
    ]
  }
]

[[repos]]
repo = "https://github.com/mit-d/check-unicode"
rev = "9d217f6f91d9e2de6bc31b54575ff35e595173f5"  # frozen: v0.6.0
hooks = [
  { id = "check-unicode",
    args = [
      "--allow-printable",
      "--check-confusables",
    ]
  }
]
