version: 2

references:
  ubuntu16: &ubuntu16
    docker:
      - image: glotzerlab/ci:2018.09-ubuntu16.04
        environment:
          PYTHONPATH: /home/ci/project/build
    working_directory: /home/ci/project

  ubuntu18: &ubuntu18
    docker:
      - image: glotzerlab/ci:2018.09-ubuntu18.04
        environment:
          PYTHONPATH: /home/ci/project/build
    working_directory: /home/ci/project

  load_code: &load_code
    checkout:
      path: code

  configure: &configure
    run:
      name: Configure
      command: mkdir build && cd build && ${CMAKE} ../code -DPYTHON_EXECUTABLE=/usr/bin/python${PYVER} -DCYTHON_EXECUTABLE=`which cython3` -GNinja

  compile: &compile
    run:
      name: Compile
      command: cd build && ninja

  unit_test: &unit_test
    run:
      name: Unit test
      command: mkdir test-results && cd code && nosetests3 --with-xunit --xunit-file=/home/ci/project/test-results/test.xml

  store_results: &store_results
    store_artifacts:
      path: test-results
      destination: test-results

  store_results2: &store_results2
    store_test_results:
      path: test-results

  build_and_test: &build_and_test
    steps:
      - *load_code
      - *configure
      - *compile
      - *unit_test
      - *store_results
      - *store_results2

jobs:
  gcc54-py35:
    <<: *ubuntu16

    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
      CMAKE: /usr/bin/cmake
      PYVER: "3.5"
    <<: *build_and_test

  gcc48-py35-cm28:
    <<: *ubuntu16
    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
      PYVER: "3.5"
      PYTEST: "py.test-3.5"
      CMAKE: /opt/cmake-2.8.12/bin/cmake
    <<: *build_and_test

  clang38-py35:
    <<: *ubuntu16
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
      PYVER: "3.5"
      PYTEST: "py.test-3.5"
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  gcc6-py36:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/gcc-6
      CXX: /usr/bin/g++-6
      PYVER: "3.6"
      PYTEST: "py.test-3"
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  gcc7-py36:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/gcc-7
      CXX: /usr/bin/g++-7
      PYVER: "3.6"
      PYTEST: "py.test-3"
      CMAKE: /usr/bin/cmake

    steps:
      - *load_code
      - *configure
      - *compile
      - *unit_test
      - *store_results
      - *store_results2
      - persist_to_workspace:
          root: .
          paths:
            - build/gsd

  sphinx-docs:
    <<: *ubuntu18
    steps:
      - *load_code
      - attach_workspace:
          at: .
      - run: cd code/doc && sphinx-build -b html -d _build/doctrees -W -n . _build/html


  gcc8-py36:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/gcc-8
      CXX: /usr/bin/g++-8
      PYVER: "3.6"
      PYTEST: "py.test-3"
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  clang4-py36:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/clang-4.0
      CXX: /usr/bin/clang++-4.0
      PYVER: "3.6"
      PYTEST: "py.test-3"
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  clang5-py36:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/clang-5.0
      CXX: /usr/bin/clang++-5.0
      PYVER: "3.6"
      PYTEST: "py.test-3"
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  clang6-py36:
    <<: *ubuntu18
    environment:
      CC: /usr/bin/clang-5.0
      CXX: /usr/bin/clang++-5.0
      PYVER: "3.6"
      PYTEST: "py.test-3"
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

workflows:
  version: 2
  workflow:
    jobs:
      - gcc54-py35
      - gcc48-py27-cm28
      - gcc6-py36
      - gcc7-py36
      - sphinx-docs:
          requires:
            - gcc7-py36
      - gcc8-py36
      - clang38-py35
      - clang4-py36
      - clang5-py36
      - clang6-py36
