version: 2

references:
  test_container_config: &test_container_config
    docker:
      - image: joaander/ci:20170807-1
        environment:
          PYTHONPATH: /root/project/build
    working_directory: /root/project

  conda_container_config: &conda_container_config
    docker:
      - image: joaander/conda-build:20170808-1
    working_directory: /root/project

  load_code: &load_code
    checkout:
      path: code

  configure: &configure
    run:
      name: Configure
      command: mkdir build && cd build && ${CMAKE} ../code -DPYTHON_EXECUTABLE=`which python3` -DCYTHON_EXECUTABLE=`which cython3` -GNinja

  compile: &compile
    run:
      name: Compile
      command: cd build && ninja

  unit_test: &unit_test
    run:
      name: Unit test
      command: mkdir test-results && cd code && nosetests3 --with-xunit --xunit-file=/root/project/test-results/test.xml

  store_results: &store_results
    store_artifacts:
      path: test-results
      destination: test-results

  store_results2: &store_results2
    store_test_results:
      path: test-results

  build_and_test: &build_and_test
    steps:
      - *load_code
      - *configure
      - *compile
      - *unit_test
      - *store_results
      - *store_results2

  conda_build: &conda_build
    steps:
      - *load_code
      - run:
          name: Compile
          working_directory: code
          command: conda build --python ${PYVER} conda-recipe
      - run: mv /opt/conda/conda-bld .
      - persist_to_workspace:
          root: .
          paths:
            - conda-bld/linux-64/gsd-*.tar.bz2

jobs:

  gcc54-python35:
    <<: *test_container_config

    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
      CMAKE: /usr/bin/cmake

    steps:
      - *load_code
      - *configure
      - *compile
      - *unit_test
      - *store_results
      - *store_results2
      - persist_to_workspace:
          root: .
          paths:
            - build/gsd

  sphinx-docs:
    <<: *test_container_config
    steps:
      - *load_code
      - attach_workspace:
          at: .
      - run: cd code/doc && sphinx-build -b html -d _build/doctrees -W -n . _build/html

  clang38-python35:
    <<: *test_container_config
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  gcc48-python35-cmake28:
    <<: *test_container_config
    environment:
      CC: /usr/bin/gcc-4.8
      CXX: /usr/bin/g++-4.8
      CMAKE: /opt/cmake-2.8.12/bin/cmake
    <<: *build_and_test

  gcc49-python35:
    <<: *test_container_config
    environment:
      CC: /usr/bin/gcc-4.9
      CXX: /usr/bin/g++-4.9
      CMAKE: /usr/bin/cmake
    <<: *build_and_test

  conda-build-python36:
    <<: *conda_container_config
    environment:
      PYVER: "3.6"
    <<: *conda_build

  conda-build-python35:
    <<: *conda_container_config
    environment:
      PYVER: "3.5"
    <<: *conda_build

  conda-build-python34:
    <<: *conda_container_config
    environment:
      PYVER: "3.4"
    <<: *conda_build

  conda-build-python27:
    <<: *conda_container_config
    environment:
      PYVER: "2.7"
    <<: *conda_build

  conda-upload:
    <<: *conda_container_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload
          command: anaconda -t ${ANACONDA_TOKEN} upload conda-bld/linux-64/gsd-*.tar.bz2

workflows:
  version: 2
  workflow:
    jobs:
      - gcc54-python35
      - sphinx-docs:
          requires:
            - gcc54-python35
      - clang38-python35
      - gcc48-python35-cmake28
      - gcc49-python35
      - conda-build-python36:
          filters:
            tags:
              only: /.*/
      - conda-build-python35:
          filters:
            tags:
              only: /.*/
      - conda-build-python34:
          filters:
            tags:
              only: /.*/
      - conda-build-python27:
          filters:
            tags:
              only: /.*/
      - conda-upload:
          context: org-global
          requires:
            - conda-build-python36
            - conda-build-python35
            - conda-build-python34
            - conda-build-python27
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
