version: 2
jobs:
  build:
    docker:
      - image: joaander/ci
    steps:
      - checkout: code
      - run: mkdir build && cd build
      - run: cmake ../code -DPYTHON_EXECUTABLE=`which python3` -DCYTHON_EXECUTABLE=`which cython3`
      - run: make
