version: 2
jobs:
  build:
    docker:
      - image: joaander/ci
    steps:
      - checkout:
          path: code
      - run: mkdir build
      - run: cd build && cmake ../code -DPYTHON_EXECUTABLE=`which python3` -DCYTHON_EXECUTABLE=`which cython3`
      - run: cd build && make
