name: Bug report
description: Report a problem with GSD.
labels: ['bug']
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Script
      description: |
        The *minimal* script that demonstrates the problem. The script should depend only on
        GSD and its dependencies so that developers can run it.
      placeholder: |
        import gsd
        ...
      render: python
    validations:
      required: true
  - type: textarea
    attributes:
      label: Input files
      description: Attach any input files needed to run the script.
  - type: textarea
    attributes:
      label: Output
      description: |
        What output did you get?
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected output
      description: What output do you expect?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Platform
      description: What platform are you using? Select all that apply.
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation method
      description: How did you install GSD?
      options:
        - Compiled from source
        - Conda package
        - glotzerlab-software container
        - PyPI package
    validations:
      required: true
  - type: input
    attributes:
      label: GSD
      description: |
        What version of GSD are you using?
      placeholder: 2.7.0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Run `python3 -c "import gsd; print(gsd.__version__)"` to find your GSD version.
  - type: input
    attributes:
      label: Python version
      description: What version of Python are you using?
      placeholder: 3.10.6
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Run `python3 --version` to find your Python version.
