blank_issues_enabled: true
contact_links:
  - name: HOOMD-blue users mailing list
    url: https://groups.google.com/d/forum/hoomd-users
    about: Ask for support from the HOOMD-blue / GSD user community.
  - name: GSD documentation
    url: https://gsd.readthedocs.io/
    about: User documentation.
