blank_issues_enabled: true
contact_links:
  - name: GSD discussion board
    url: https://github.com/glotzerlab/gsd/discussions/
    about: Ask the GSD user community for help.
  - name: GSD documentation
    url: https://gsd.readthedocs.io/
    about: User documentation.
