name: Feature request
description: Suggest a new GSD feature
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Description
      description: What new capability would you like in GSD?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: How should this capability be implemented? What might the user API look like?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: What additional information is helpful to understand this request?
  - type: dropdown
    attributes:
      label: Developer
      description: Who should implement the new functionality?
      multiple: false
      options:
        - I will submit a pull request that implements this feature.
        - Would someone else please implement this?
  - type: markdown
    attributes:
      value: |
        We would welcome your contribution!

        If you plan to implement this functionality, the GSD developers will discuss the
        proposed design and API with you **before** you begin work.
