steps:
- checkout: self
  submodules: true

- task: CMake@1
  inputs:
    cmakeArgs: $(Build.SourcesDirectory)
    workingDirectory: $(Build.BinariesDirectory)

- script: cmake --build . --config Release --target all
  displayName: Compile
  workingDirectory: $(Build.BinariesDirectory)
