package:
  name: gsd
  version: "0.0.0"

build:
  number: 0

source:
  path: ../

requirements:
  build:
    - nomkl
    - python
    - numpy
    - cython
    - cmake

  run:
    - python
    - numpy

test:
  imports:
    - gsd
    - gsd.fl
    - gsd.pygsd
    - gsd.hoomd

about:
  home: https://bitbucket.org/glotzer/gsd
  license: BSD 2-clause

