variables:
  image_root: glotzerlab/ci:2021.03
  python: python3
  pytest_options: -p gsd.pytest_plugin_validate --validate

# Trigger on PRs into stable branches.
pr:
  - maint
  - master

# Do not trigger on every push. This runs every commit twice for PRs with branches on the main
# repository.
trigger: none

# Instead, trigger periodic builds on active branches.
schedules:
- cron: "0 3-21/6 * * *"
  displayName: Periodic build
  branches:
    include:
    - "*"

stages:
- stage: build_test
  displayName: Unit test
  dependsOn: []

  jobs:
  - job: linux_cpu
    displayName: Linux
    strategy:
      # the matrix job name sets the name of the docker image
      matrix:
        clang11_py39:
          unused: ""
        gcc10_py39:
          unused: ""
        gcc9_py38:
          unused: ""
        clang10_py38:
          unused: ""
        clang9_py38:
          unused: ""
        clang8_py38:
          unused: ""
        clang7_py38:
          unused: ""
        gcc8_py37:
          unused: ""
        gcc7_py37:
          unused: ""
        clang6_py37:
          unused: ""
        gcc7_py36:
          unused: ""

    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: $(image_root)-$(System.JobName)
      options: -u 0

    steps:
    - template: templates/build.yml
    - template: templates/unit_test.yml

  - job: mac
    displayName: Mac

    strategy:
      matrix:
        mac10_14:
          mac_image: macOS-10.14

        mac10_15:
          mac_image: macOS-10.15

    pool:
      vmImage: '$(mac_image)'

    steps:
    - script: brew install python cmake ninja
      displayName: Brew install prereqs
    - script: $(python) -m pip --disable-pip-version-check install pytest cython numpy
      displayName: Pip install prereqs
    - template: templates/build.yml
    - template: templates/unit_test.yml

  - job: win_cmake
    displayName: Win (CMake)

    strategy:
      matrix:
        vs2017_py37_x64:
          win_image: vs2017-win2016
          python_version: 3.7
          python: python            # windows images use `python`, not `python3`
          CMAKE_GENERATOR: Visual Studio 15 2017
          CMAKE_GENERATOR_PLATFORM: x64
          architecture: 'x64'
        vs2019_py39_x64:
          win_image: windows-2019
          python_version: 3.9
          python: python            # windows images use `python`, not `python3`
          CMAKE_GENERATOR: Visual Studio 16 2019
          CMAKE_GENERATOR_PLATFORM: x64
          architecture: 'x64'
        vs2019_py38_x64:
          win_image: windows-2019
          python_version: 3.8
          python: python            # windows images use `python`, not `python3`
          CMAKE_GENERATOR: Visual Studio 16 2019
          CMAKE_GENERATOR_PLATFORM: x64
          architecture: 'x64'
        vs2019_py37_x64:
          win_image: windows-2019
          python_version: 3.7
          python: python            # windows images use `python`, not `python3`
          CMAKE_GENERATOR: Visual Studio 16 2019
          CMAKE_GENERATOR_PLATFORM: x64
          architecture: 'x64'
        vs2019_py36_x64:
          win_image: windows-2019
          python_version: 3.6
          python: python            # windows images use `python`, not `python3`
          CMAKE_GENERATOR: Visual Studio 16 2019
          CMAKE_GENERATOR_PLATFORM: x64
          architecture: 'x64'
        vs2019_py37_x32:
          win_image: windows-2019
          python_version: 3.7
          python: python            # windows images use `python`, not `python3`
          CMAKE_GENERATOR: Visual Studio 16 2019
          CMAKE_GENERATOR_PLATFORM: Win32
          architecture: 'x86'
          pytest_options:

    pool:
      vmImage: '$(win_image)'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python_version)
        addToPath: true
        architecture: $(architecture)
    - powershell: $(python) -m pip --disable-pip-version-check install numpy cython pytest
      displayName: Pip install prereqs
    - template: templates/build.yml
    - powershell: cp .\gsd\Release\*.pyd gsd\
      workingDirectory: $(Build.BinariesDirectory)
      displayName: Copy pyd files
    - template: templates/unit_test.yml

- stage: os_packages
  displayName: OS Packages
  dependsOn: []

  jobs:
  - job: ubuntu_20_04
    displayName: Ubuntu 20.04
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: ubuntu:20.04
      options:  "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

    steps:
    # workaround documented here: https://github.com/Microsoft/azure-pipelines-agent/issues/2043#issuecomment-687983301
    - script: |
        /tmp/docker exec -t -u 0 ci-container \
        sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install \
          sudo \
          python3-numpy \
          cython3 \
          python3-pytest \
          build-essential \
          ninja-build \
          cmake"
      displayName: 'Install dependencies'
    - template: templates/build.yml
    - template: templates/unit_test.yml

- stage: doc
  displayName: Documentation
  dependsOn: []

  jobs:
  - job: sphinx_doc
    displayName: Sphinx
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: $(image_root)-gcc7_py37
      options: -u 0

    workspace:
      clean: all

    steps:
    - template: templates/build.yml
    - template: templates/sphinx_doc.yml

- stage: style
  displayName: Style checks
  dependsOn: []

  jobs:
  - job: clang_format
    displayName: clang-format
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: $(image_root)-clang10_py38
      options: -u 0

    workspace:
      clean: all

    steps:
    - checkout: self
      submodules: true
    - script: ./run-clang-format.py -r scripts gsd
      displayName: Run clang-format

  - job: clang_tidy
    displayName: clang-tidy
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: $(image_root)-clang10_py38
      options: -u 0

    workspace:
      clean: all

    steps:
    - checkout: self
      submodules: true

    - task: CMake@1
      inputs:
        cmakeArgs: $(Build.SourcesDirectory)
        workingDirectory: $(Build.BinariesDirectory)

    - script: clang-tidy -p=$(Build.BinariesDirectory) gsd/*.c gsd/*.h scripts/*.cc --quiet --warnings-as-errors="*"
      displayName: Run clang-tidy

  - job: flake8
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: $(image_root)-clang10_py38
      options: -u 0

    workspace:
      clean: all

    steps:
    - checkout: self
      submodules: true

    - script: flake8
      displayName: Run flake8

  - job: yapf
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: $(image_root)-clang10_py38
      options: -u 0

    workspace:
      clean: all

    steps:
    - checkout: self
      submodules: true

    - script: yapf -d -r .
      displayName: Run yapf
