name: PyPI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
      - "trunk-*"
    tags:
      - "v*"

  workflow_dispatch:

env:
  UV_VERSION: 0.2.2

jobs:
  build_wheels:
    name: Build wheels [py${{ matrix.python_version }}, ${{ matrix.os }}]
    runs-on: ${{ matrix.os }}-${{ matrix.os_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

        include:
          - os_version: 'latest'

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: "==${{ matrix.python_version }}.*"

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: dist-python-${{ matrix.python_version }}-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      - uses: actions/setup-python@v5.1.0
        name: Install Python
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/${{ env.UV_VERSION }}/uv-installer.sh | bash

      - name: Install build
        run: 'uv pip install -r .github/requirements-build-sdist.txt --only-binary :all: --system --reinstall'

      - name: Build sdist
        run: python -m build --sdist --outdir dist/ .

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: dist-sdist
          path: dist/*.tar.gz

  upload_pypi:
    name: Publish [PyPI]
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          merge-multiple: 'true'
          pattern: dist-*
          path: dist

      - name: Check files
        run: ls -lR dist

      - name: Upload to PyPI
        # upload to PyPI on every tag starting with 'v'
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload to TestPyPI
        # otherwise, upload to TestPyPi
        if: ${{ !startsWith(github.ref, 'refs/tags/v') && (github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]')) }}
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
