name: Style check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
      - "trunk-*"

  workflow_dispatch:

jobs:
  clang-tidy:
    name: Run clang-tidy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.12
      - name: Set up Python environment
        uses: glotzerlab/workflows/setup-uv@a36a97114c60241b26217ce92abbb64621ac67c7 # 0.6.0
        with:
          lockfile: ".github/requirements-test.txt"
      - name: Configure
        run: cmake -B build
      - name: Execute clang-tidy
        run: clang-tidy-18 -p=build gsd/*.c gsd/*.h scripts/*.cc --quiet --warnings-as-errors="*"

  # This job is used to provide a single requirement for branch merge conditions.
  checks_complete:
    name: Style check
    if: always()
    needs: [clang-tidy]
    runs-on: ubuntu-latest

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
