name: Style check

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
      - "trunk"

  workflow_dispatch:

jobs:
  clang-tidy:
    name: Run clang-tidy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.14
      - name: Set up Python environment
        uses: glotzerlab/workflows/setup-uv@00c67cb577c36bdc2570845fc62d1a30e3383012 # 0.14.0
        with:
          lockfile: ".github/requirements-test.txt"
      - name: Configure
        run: cmake -B build
      - name: Execute clang-tidy
        run: clang-tidy-18 -p=build gsd/*.c gsd/*.h scripts/*.cc --quiet --warnings-as-errors="*"

  prek:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: prek
      uses: j178/prek-action@5337cb91e0fa35a7ff31b9ca345126d8bbbcdf16 # v2.0.6
      with:
        prek-version: '0.3.8'

  # This job is used to provide a single requirement for branch merge conditions.
  tests_complete:
    name: All style checks
    if: always()
    needs: [clang-tidy, prek]
    runs-on: ubuntu-24.04

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
