name: Style checks

env:
  image_prefix: glotzerlab/ci:2021.03
  pytest_options: -p gsd.pytest_plugin_validate --validate

on:
  # Trigger on pull requests.
  pull_request:

  # Trigger on pushes to the mainline branches and version tags. This prevents building commits
  # twice when the pull request source branch is in the same repository.
  push:
    branches:
      - "maint"
      - "master"

  # Trigger on request.
  workflow_dispatch:

jobs:
  style_checks:
    name: Run ${{ matrix.name }}
    runs-on: ubuntu-latest
    container:
      image: ${{ env.image_prefix }}-clang10_py38
      options: -u 0
    strategy:
      matrix:
        include:
          - name: clang_format
            command: ./run-clang-format.py -r scripts gsd
          - name: clang_tidy
            command: clang-tidy -p=build gsd/*.c gsd/*.h scripts/*.cc --quiet --warnings-as-errors="*"
          - name: flake8
            command: flake8
          - name: yapf
            command: yapf -d -r .
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Configure
        run: cmake -B build
      - name: Execute ${{ matrix.name }}
        run: ${{ matrix.command }}
